# This is a basic workflow to help you get started with Actions

name: BuildV8

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check_V8
        uses: actions/checkout@master
        with:
          repository: https://github.com/v8/v8.git

      - name: Checkout_Depot_Tools
        uses: actions/checkout@master
        with:
          repository: https://chromium.googlesource.com/chromium/tools/depot_tools.git
